language: node_js
node_js: 8.8.1
script:
  - npm run flow
  - npm test
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: >
    npm config set '//registry.npmjs.org/:_authToken' "$NPM_TOKEN";
    git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git;
    npm version patch -m "v%s [ci skip]";
    cp README.md LICENSE package.json target/out;
    git push origin HEAD:$TRAVIS_BRANCH;
    cd target/out;
    npm publish;
  on:
    branch: master